"""add content_gap_report fields

Revision ID: 8e7b9c1d2e3f
Revises: cf3eedfda4c5
Create Date: 2026-03-06 17:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e7b9c1d2e3f'
down_revision: Union[str, Sequence[str], None] = 'cf3eedfda4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('content_gap_report', sa.JSON(), nullable=True))
    op.add_column('serp_cache', sa.Column('content_gap_report', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serp_cache', 'content_gap_report')
    op.drop_column('projects', 'content_gap_report')
    # ### end Alembic commands ###
