"""Add foreign keys and relationships v2

Revision ID: be98247c8056
Revises: 6a7b8c9d0e1f
Create Date: 2026-03-18 16:56:27.936582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be98247c8056'
down_revision: Union[str, Sequence[str], None] = '6a7b8c9d0e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cms_configs', schema=None, recreate='always') as batch_op:
        batch_op.create_foreign_key('fk_cms_configs_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('credit_logs', schema=None, recreate='always') as batch_op:
        batch_op.create_foreign_key('fk_credit_logs_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('kalpa_matrices', schema=None, recreate='always') as batch_op:
        batch_op.create_foreign_key('fk_kalpa_matrices_user_id', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_kalpa_matrices_cms_config_id', 'cms_configs', ['cms_config_id'], ['id'])

    with op.batch_alter_table('kalpa_nodes', schema=None, recreate='always') as batch_op:
        batch_op.add_column(sa.Column('images', sa.JSON(), nullable=True))
        batch_op.create_foreign_key('fk_kalpa_nodes_matrix_id', 'kalpa_matrices', ['matrix_id'], ['id'])
        batch_op.create_foreign_key('fk_kalpa_nodes_user_id', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_kalpa_nodes_cms_config_id', 'cms_configs', ['cms_config_id'], ['id'])

    with op.batch_alter_table('keyword_cache', schema=None, recreate='always') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_keyword_cache_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('projects', schema=None, recreate='always') as batch_op:
        batch_op.add_column(sa.Column('content_gap_report', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('images', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('quality_report', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('last_audit_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_projects_user_id', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_projects_cms_config_id', 'cms_configs', ['cms_config_id'], ['id'])

    with op.batch_alter_table('prompt_templates', schema=None, recreate='always') as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_prompt_templates_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('serp_cache', schema=None, recreate='always') as batch_op:
        batch_op.add_column(sa.Column('content_gap_report', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('serp_cache', schema=None) as batch_op:
        batch_op.drop_column('content_gap_report')

    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_prompt_templates_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_projects_user_id'))
        batch_op.drop_column('last_audit_at')
        batch_op.drop_column('quality_report')
        batch_op.drop_column('images')
        batch_op.drop_column('content_gap_report')

    with op.batch_alter_table('keyword_cache', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_keyword_cache_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('kalpa_nodes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_kalpa_nodes_user_id'))
        batch_op.drop_column('images')

    with op.batch_alter_table('kalpa_matrices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_kalpa_matrices_user_id'))

    with op.batch_alter_table('credit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('cms_configs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cms_configs_user_id'))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###
