"""Phase 3 Catch-up: Add user management, credits, CMS, and Kalpa Matrix

Revision ID: cf3eedfda4c5
Revises: 72fdfa1d656b
Create Date: 2026-03-03 16:11:13.980999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf3eedfda4c5'
down_revision: Union[str, Sequence[str], None] = '72fdfa1d656b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('api_url', sa.Text(), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('auto_publish_enabled', sa.Boolean(), nullable=True),
    sa.Column('frequency_type', sa.String(length=20), nullable=True),
    sa.Column('frequency_count', sa.Integer(), nullable=True),
    sa.Column('last_auto_published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_configs_user_id'), 'cms_configs', ['user_id'], unique=False)
    op.create_table('credit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_logs_user_id'), 'credit_logs', ['user_id'], unique=False)
    op.create_table('kalpa_matrices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('money_page_url', sa.Text(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('pain_points', sa.JSON(), nullable=True),
    sa.Column('anchor_variants', sa.JSON(), nullable=True),
    sa.Column('cms_config_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kalpa_matrices_project_name'), 'kalpa_matrices', ['project_name'], unique=False)
    op.create_index(op.f('ix_kalpa_matrices_user_id'), 'kalpa_matrices', ['user_id'], unique=False)
    op.create_table('kalpa_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('matrix_id', sa.String(length=36), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('pain_point', sa.String(length=100), nullable=True),
    sa.Column('target_title', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('woven_content', sa.Text(), nullable=True),
    sa.Column('anchor_used', sa.String(length=255), nullable=True),
    sa.Column('woven_at', sa.DateTime(), nullable=True),
    sa.Column('cms_config_id', sa.String(length=36), nullable=True),
    sa.Column('cms_post_id', sa.String(length=100), nullable=True),
    sa.Column('publish_status', sa.String(length=20), nullable=True),
    sa.Column('cms_publish_url', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kalpa_nodes_matrix_id'), 'kalpa_nodes', ['matrix_id'], unique=False)
    op.create_index(op.f('ix_kalpa_nodes_user_id'), 'kalpa_nodes', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('membership_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('keyword_cache', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_keyword_cache_user_id'), 'keyword_cache', ['user_id'], unique=False)
    op.add_column('projects', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.add_column('projects', sa.Column('cms_config_id', sa.String(length=36), nullable=True))
    op.add_column('projects', sa.Column('cms_post_id', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('publish_status', sa.String(length=20), nullable=True))
    op.add_column('projects', sa.Column('cms_publish_url', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.add_column('prompt_templates', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_prompt_templates_user_id'), 'prompt_templates', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_templates_user_id'), table_name='prompt_templates')
    op.drop_column('prompt_templates', 'user_id')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_column('projects', 'published_at')
    op.drop_column('projects', 'scheduled_at')
    op.drop_column('projects', 'cms_publish_url')
    op.drop_column('projects', 'publish_status')
    op.drop_column('projects', 'cms_post_id')
    op.drop_column('projects', 'cms_config_id')
    op.drop_column('projects', 'user_id')
    op.drop_index(op.f('ix_keyword_cache_user_id'), table_name='keyword_cache')
    op.drop_column('keyword_cache', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_kalpa_nodes_user_id'), table_name='kalpa_nodes')
    op.drop_index(op.f('ix_kalpa_nodes_matrix_id'), table_name='kalpa_nodes')
    op.drop_table('kalpa_nodes')
    op.drop_index(op.f('ix_kalpa_matrices_user_id'), table_name='kalpa_matrices')
    op.drop_index(op.f('ix_kalpa_matrices_project_name'), table_name='kalpa_matrices')
    op.drop_table('kalpa_matrices')
    op.drop_index(op.f('ix_credit_logs_user_id'), table_name='credit_logs')
    op.drop_table('credit_logs')
    op.drop_index(op.f('ix_cms_configs_user_id'), table_name='cms_configs')
    op.drop_table('cms_configs')
    # ### end Alembic commands ###
