"""add quality audit persistence fields

Revision ID: e9f2a8b7c6d5
Revises: 8e7b9c1d2e3f
Create Date: 2026-03-09 13:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f2a8b7c6d5'
down_revision: Union[str, Sequence[str], None] = '8e7b9c1d2e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('quality_report', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('last_audit_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'last_audit_at')
    op.drop_column('projects', 'quality_report')
    # ### end Alembic commands ###
